import type { SportConfig } from '../types';

export const SPORTS_CONFIG: Record<string, SportConfig> = {
  football: {
    name: 'football',
    minPlayers: 6,
    maxPlayers: 8,
    requiresKitNumber: true,
    tournaments: [
      {
        id: 'mens-football',
        name: "Men's Football Tournament",
        category: 'mens',
        minPlayers: 6,
        maxPlayers: 8,
        registrationFee: 10000,
        prizePool: 1150000,
      },
      {
        id: 'womens-football',
        name: "Women's Football Tournament",
        category: 'womens',
        minPlayers: 6,
        maxPlayers: 8,
        registrationFee: 6000,
        prizePool: 800000,
      },
    ],
    image:
      'https://i.postimg.cc/kXBD38tF/jason-charters-Iorqs-Mss-QH0-unsplash.jpg',
    schedule: {
      days: 'March 7-9, 2025',
      time: '7:00 PM - 1:00 AM',
      format: 'Group stages followed by knockouts',
      details: [
        'Group matches: 7:00 PM - 10:00 PM',
        'Knockout matches: 10:30 PM - 1:00 AM',
        'Finals on March 9: 11:00 PM',
      ],
    },
  },
  padel: {
    name: 'padel',
    minPlayers: 2,
    maxPlayers: 2,
    requiresKitNumber: false,
    tournaments: [
      {
        id: 'padel-a',
        name: 'Level A Tournament',
        category: 'a',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1500,
        prizePool: 200000,
      },
      {
        id: 'padel-b',
        name: 'Level B Tournament',
        category: 'b',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1200,
        prizePool: 150000,
      },
      {
        id: 'padel-c',
        name: 'Level C Tournament',
        category: 'c',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1100,
        prizePool: 100000,
      },
      {
        id: 'padel-d',
        name: 'Level D Tournament',
        category: 'd',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1000,
        prizePool: 75000,
      },
    ],
    image: 'https://i.postimg.cc/vBhDMtzX/tim-chow-rb-Gg2-Vl-Ilpg-unsplash.jpg',
    schedule: {
      days: 'March 10-12, 2025',
      time: '8:00 PM - 1:30 AM',
      format: 'Level-based round-robin',
      details: [
        'Level A & B: 8:00 PM - 11:00 PM',
        'Level C & D: 11:00 PM - 1:30 AM',
        'Finals on March 12: 10:00 PM',
      ],
    },
  },
  basketball: {
    name: 'basketball',
    minPlayers: 4,
    maxPlayers: 5,
    requiresKitNumber: true,
    tournaments: [
      {
        id: 'mens-basketball',
        name: "Men's 3v3 Basketball",
        category: 'mens',
        minPlayers: 3,
        maxPlayers: 4,
        registrationFee: 1500,
        prizePool: 200000,
      },
      {
        id: 'womens-basketball',
        name: "Women's 3v3 Basketball",
        category: 'womens',
        minPlayers: 3,
        maxPlayers: 4,
        registrationFee: 1500,
        prizePool: 200000,
      },
    ],
    image: 'https://i.postimg.cc/05trBZry/pexels-cachi290-29889785.jpg',
    schedule: {
      days: 'March 13-15, 2025',
      time: '7:30 PM - 12:30 AM',
      format: 'Pool play to single elimination',
      details: [
        'Pool games: 7:30 PM - 10:30 PM',
        'Elimination rounds: 10:30 PM - 12:30 AM',
        'Finals on March 15: 11:00 PM',
      ],
    },
  },
  padbol: {
    name: 'padbol',
    minPlayers: 2,
    maxPlayers: 2,
    requiresKitNumber: false,
    tournaments: [
      {
        id: 'padbol-a',
        name: 'Level A Tournament',
        category: 'a',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 750,
        prizePool: 100000,
      },
      {
        id: 'padbol-b',
        name: 'Level B Tournament',
        category: 'b',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 650,
        prizePool: 75000,
      },
    ],
    image:
      'https://i.postimg.cc/yxrd362Z/outdoors-mini-football-and-basketball-court-with-b-2023-11-27-05-12-07-utc.jpg',
    schedule: {
      days: 'March 16-18, 2025',
      time: '8:30 PM - 1:00 AM',
      format: 'Double elimination bracket',
      details: [
        'Winners bracket: 8:30 PM - 11:00 PM',
        'Losers bracket: 11:00 PM - 1:00 AM',
        'Finals on March 18: 10:30 PM',
      ],
    },
  },
};
