import { SportConfig } from '../types';

export const SPORTS_CONFIG: Record<string, SportConfig> = {
  Football: {
    name: 'Football',
    minPlayers: 6,
    maxPlayers: 8,
    requiresKitNumber: true,
    tournaments: [
      {
        id: 'mens-football',
        name: "Men's Football Tournament",
        category: 'mens',
        minPlayers: 6,
        maxPlayers: 8,
        registrationFee: 10000,
        prizePool: 1000000,
      },
      {
        id: 'womens-football',
        name: "Women's Football Tournament",
        category: 'womens',
        minPlayers: 6,
        maxPlayers: 8,
        registrationFee: 6000,
        prizePool: 500000,
      },
    ],
  },
  Padel: {
    name: 'Padel',
    minPlayers: 2,
    maxPlayers: 2,
    requiresKitNumber: false,
    tournaments: [
      {
        id: 'padel-a',
        name: 'Level A Tournament',
        category: 'a',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1500,
        prizePool: 200000,
      },
      {
        id: 'padel-b',
        name: 'Level B Tournament',
        category: 'b',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1200,
        prizePool: 150000,
      },
      {
        id: 'padel-c',
        name: 'Level C Tournament',
        category: 'c',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1100,
        prizePool: 100000,
      },
      {
        id: 'padel-d',
        name: 'Level D Tournament',
        category: 'd',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1000,
        prizePool: 75000,
      },
    ],
  },
  Basketball: {
    name: 'Basketball',
    minPlayers: 4,
    maxPlayers: 5,
    requiresKitNumber: true,
    tournaments: [
      {
        id: 'mens-basketball',
        name: "Men's 3v3 Basketball",
        category: 'mens',
        minPlayers: 3,
        maxPlayers: 4,
        registrationFee: 1500,
        prizePool: 200000,
      },
      {
        id: 'womens-basketball',
        name: "Women's 3v3 Basketball",
        category: 'womens',
        minPlayers: 3,
        maxPlayers: 4,
        registrationFee: 1500,
        prizePool: 200000,
      },
    ],
  },
  Padbol: {
    name: 'Padbol',
    minPlayers: 2,
    maxPlayers: 2,
    requiresKitNumber: false,
    tournaments: [
      {
        id: 'padbol-a',
        name: 'Level A Tournament',
        category: 'a',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 750,
        prizePool: 100000,
      },
      {
        id: 'padbol-b',
        name: 'Level B Tournament',
        category: 'b',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 650,
        prizePool: 75000,
      },
      {
        id: 'padbol-combo',
        name: 'Level A & B Package',
        category: 'combo',
        minPlayers: 2,
        maxPlayers: 2,
        registrationFee: 1200,
        prizePool: 175000,
      },
    ],
  },
};
